### ISSUE TITLE
Write to CSV?

### ISSUE THREAD

**Issue by ChrisRackauckas** [davidanthoff/IterableTables.jl#23]
I was trying to find out how to write to a CSV. I only see it used as a source here:

https://github.com/davidanthoff/IterableTables.jl/blob/master/test/test_integration_datastreams.jl

I was wondering if it's able to be used as a sink as well. The best I could find was to write to a dataframe and then write that to a CSV. I assume there's something direct that I am just not finding?

**Comment by davidanthoff** [comment]
The function ``IterableTables.get_datastreams_source`` will wrap an iterable table as a ``DataStreams`` ``Sink``, and from there on you can just use the standard methods from say [CSV](). So in practice you have to write something like this:
````julia
CSV.write("test.csv", IterableTables.get_datastreams_source(sol))
````
I'm not super happy about the whole ``get_datastreams_source`` detour, and that is why I'm not exporting that function for now, still trying to figure out something more elegant.

I also at some point wrote a CsvWriter in [Query](https://github.com/davidanthoff/Query.jl) that operated directly on iterable tables and avoided the whole ``DataStreams`` object model. That code is still [here](https://github.com/davidanthoff/Query.jl/blob/master/src/sinks/sink_csvfile.jl), but right now it really is only accessible from within a query. Maybe I should just dust that off and put it into its own package, so that one could just write:
````julia
csvwrite("test.csv", sol)
````
It wouldn't be much work at all....

**Comment by davidanthoff** [comment]
Alright, the CSV writer is now fully integrated with IterableTables and FileIO. You can write any iterable table to a CSV file like this:
````julia
using FileIO, IterableTables

save("filename.csv", source)
````
Or you can use the new piping syntax:
````julia
source |> save("filename.csv")
````
