### ISSUE TITLE
Schema has no field types

### ISSUE THREAD

**Issue by pfarndt** [davidanthoff/IterableTables.jl#69]
When trying to convert a SQLite source to a DataFrame I get the following error:

type Schema has no field types

Stacktrace:
 [1] getiterator(::SQLite.Source) at .julia/v0.6/IterableTables/src/integrations/datastreams.jl:27
 [2] _DataFrame(::SQLite.Source) at .julia/v0.6/IterableTables/src/integrations/dataframes-missing.jl:98
 [3] DataFrames.DataFrame(::SQLite.Source) at .julia/v0.6/IterableTables/src/integrations/dataframes-missing.jl:127
....

I am using Julia v0.6.2 with:

 - IterableTables                0.6.0
 - DataFrames                    0.11.2
 - Query                         0.9.0
 - SQLite                        0.5.0
 - DataStreams                   0.3.4

**Comment by davidanthoff** [comment]
Yes, this is a known issue, the DataStreams API changed and I haven't updated things to work with the new definition.

**Comment by pstaabp** [comment]
I just ran into this learning about using these with SQLite and CSV sources.  I was thinking of looking into a bug fix for this, but looks like you may have one in the pipeline.  Any chance the fix will be released soon?

**Comment by dvignon** [comment]
Same issue here. Will a fix be released any time soon?

**Comment by davidanthoff** [comment]
I'm a bit behind on julia stuff right now. It is not clear right now to me what the future of DataStreams.jl is (mostly because I need to catch up with the various forums etc.). Until I have figured that out, I'm not sure when this will be sorted out.

For now, I would recommend that you use the normal DataStreams.jl way of converting things into a DataFrame, and then everything should work downstream via the stuff here. I'll update this here once I have a clearer picture.

**Comment by davidanthoff** [comment]
So, DataStreams.jl is a thing of the past, and I'm closing this here.

Hopefully we'll get full integration of Tables.jl at some point, and then those sources should just work again.
